# Generated by Django 4.1.4 on 2023-08-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiledesign_home', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/blog_images'),
        ),
    ]
