# Generated by Django 4.1.4 on 2023-09-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiledesign_home', '0003_remove_blog_slug_remove_doctors_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_large',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/large'),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_medium',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/medium'),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/small'),
        ),
    ]
