# Generated by Django 4.1.4 on 2023-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiledesign_home', '0005_blog_created_by_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('field_of_expertise', models.CharField(max_length=1000)),
                ('subfields', models.CharField(max_length=1000)),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to='doctors_images')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
