# Generated by Django 4.1.4 on 2023-10-05 08:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smiledesign_home', '0005_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='services_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
