# Generated by Django 4.1.4 on 2023-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smiledesign_home', '0007_alter_doctors_subfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', models.CharField(max_length=400)),
                ('services_description', models.TextField()),
                ('services_image', models.ImageField(blank=True, null=True, upload_to='services_images')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
